/*
 * pinout.h
 *
 *  Created on: Aug 29, 2013
 *      Author: Andrey Belomutskiy, (c) 2012-2013
 */

#ifndef PINOUT_H_
#define PINOUT_H_

#if EFI_CRANK_INPUT
//#define CRANK_DRIVER ICUD4
//#define CRANK_INPUT_PORT GPIOB
//#define CRANK_INPUT_PIN 6
//GPIO_AF_TIM4

#define PRIMARY_CRANK_DRIVER ICUD2
#define PRIMARY_CRANK_INPUT_PORT GPIOA
#define PRIMARY_CRANK_INPUT_PIN 5

//#define CRANK_DRIVER ICUD9
//#define CRANK_INPUT_PORT GPIOE
//#define CRANK_INPUT_PIN 5

#define SECONDARY_CRANK_DRIVER ICUD3
#define SECONDARY_CRANK_INPUT_PORT GPIOC
#define SECONDARY_CRANK_INPUT_PIN 6

//#define CRANK_DRIVER ICUD4
//#define CRANK_INPUT_PORT GPIOB
//#define CRANK_INPUT_PIN 6
#endif

#define SPARK_1_PORT GPIOD
#define SPARK_1_PIN 3

#define INJECTOR_1_PORT GPIOB
#define INJECTOR_1_PIN 8

#define INJECTOR_2_PORT GPIOB
#define INJECTOR_2_PIN 9

#define INJECTOR_3_PORT GPIOE
#define INJECTOR_3_PIN 1

#define INJECTOR_4_PORT GPIOE
#define INJECTOR_4_PIN 0

#define IDLE_VALVE_PORT GPIOE
#define IDLE_VALVE_PIN 3

#define IDLE_SWITCH_PORT GPIOC
#define IDLE_SWITCH_PIN 8

#if EFI_EMULATE_POSITION_SENSORS
#define EMULATION_FIRST_PIN 4
#define EMULATION_FIRST_PORT GPIOD

#define EMULATION_SECOND_PIN 1
#define EMULATION_SECOND_PORT GPIOD
#endif

#endif /* PINOUT_H_ */
