import java.io.*;
import java.util.Date;

/**
 * (c) Andrey Belomutskiy
 * 1/12/15.
 */
public class ConfigDefiniton {
    private static final String FILE_NAME = "rusefi_config.ini";

    public static void main(String[] args) throws IOException {
        if (args.length != 1) {
            System.out.println("Please specify path to '" + FILE_NAME + "' file");
            return;
        }
        String path = args[0];
        String fullFileName = path + File.separator + FILE_NAME;
        System.out.println("Reading from " + fullFileName);

        BufferedWriter cHeader = new BufferedWriter(new FileWriter("configuration.h_section"));
        BufferedWriter tsHeader = new BufferedWriter(new FileWriter("configuration.ts_section"));

        BufferedReader br = new BufferedReader(new FileReader(fullFileName));

        processFile(br, cHeader, tsHeader);

        cHeader.close();
        tsHeader.close();

    }

    private static void processFile(BufferedReader br, BufferedWriter cHeader, BufferedWriter tsHeader) throws IOException {
        String line;

        String message = "// this section was generated by config_definition.jar on " + new Date() + "\r\n";
        cHeader.write(message);
        cHeader.write("// begin\r\n");

        int currentOffset = 0;

        while ((line = br.readLine()) != null) {
            line = line.trim();
            if (line.startsWith("#"))
                continue;
            if (line.length() == 0)
                continue;


            String[] a = line.split(";");
            if (a.length != 3) {
                System.err.println("Three comma-separated elements expected");
            }
            String type = a[0];
            String name = a[1];
            String comment = a[2];
            System.out.println("type " + type);
            System.out.println("name " + name);
            System.out.println("comment " + comment);


            String cEntry = "\t/**\r\n\t * " + comment + "\r\n\t * offset " + currentOffset + "\r\n\t*/\r\n";

            cEntry += "\t" + type + " " + name + ";\r\n";

            cHeader.write(cEntry);

            currentOffset += 4;

        }
        cHeader.write("// end\r\n");
        cHeader.write(message);
    }
}
